### ISSUE TITLE
🔴 YouTube: "The page needs to be reloaded" — 80+ ошибок/24ч от 15+ пользователей

### ISSUE THREAD

**Issue by chelaxian** [chelaxian/tg-ytdlp-bot#436]
## Описание
При попытке скачивания YouTube видео через Always Ask menu, yt-dlp возвращает ошибку: `ERROR: [youtube] VIDEO_ID: The page needs to be reloaded.`

## Масштаб
- **80+ случаев за 24ч** (7 авг 2026)
- **15+ уникальных пользователей**
- Ошибки на regular `/watch?v=`, `/shorts/`, `/live/`, `youtu.be/` URL

## Причина
YouTube изменил frontend-логику проверки страниц. yt-dlp extractor не обрабатывает новый challenge корректно. Типично исправляется обновлением yt-dlp.

## Рекомендация
1. **Auto-update yt-dlp**: добавить ежедневный `pip install -U yt-dlp` или хотя бы при старте бота
2. **Retry with fresh extract**: при получении "page needs to be reloaded" — повторить с `--extractor-retries 3`
3. **User-friendly message**: показать пользователю понятное сообщение вместо стек-трейса

## Контекст
- Все серверы (UAE/UK/FR/IT)
- Затронуты: Always Ask menu, прямые запросы
- Ошибка началась массово ~6 авг

**Comment by chelaxian** [comment]
Fixed in commit 7fcf45c (branch proger4ever-prs).

**Root cause:** YouTube introduced a new frontend bot-detection challenge (The page needs to be reloaded). The error string was not classified anywhere in the bot's error handling — it fell through to generic extraction failure, showing 80+ users a confusing message over 24h.

**Fix (4 changes):**
1. **yt_dlp_hook.py** — Added 'page needs to be reloaded' to _PERMANENT_UNAVAILABLE_INDICATORS so get_video_formats fast-fails instead of running expensive proxy/impersonate retry storms.
2. **CONFIG/errors.py** — Added the pattern to classify_yt_dlp_error → returns EXTRACTOR_ERROR, which shows the user a clear message (yt-dlp update / try again later) instead of a raw error.
3. **down_and_up.py** — Added the error to the download-path error_code classification block as EXTRACTOR_ERROR with a user-friendly description.
4. **always_ask_menu.py** — Enhanced the PERMANENT_UNAVAILABLE handler to call classify_yt_dlp_error on the original error text, showing the specific ALWAYS_ASK_EXTRACTOR_ERROR_MSG instead of the generic NO_VIDEOS_FOUND_IN_PLAYLIST message.

Closing as completed.

**Comment by chelaxian** [comment]
**Рецидив (ежедневный мониторинг 2026-08-20, метод: SSH fallback bot.log).**

Обнаружены новые ошибки того же типа за последние ~5ч (после рестарта сервиса) на доступном для мониторинга инстансе:

- `DownloadError in get_video_formats: The page needs to be reloaded` — 12 случаев (8 уникальных видео, часть с повторами 2×)
- `Proxy fallback failed: ... The page needs to be reloaded` — 6 случаев
- `Permanent error, no retries` для этого же паттерна также присутствует

**Ключевое наблюдение:** строки `Proxy fallback failed` указывают, что прокси-фолбэк по-прежнему запускается для этой ошибки, хотя фикс (fast-fail через `_PERMANENT_UNAVAILABLE_INDICATORS`) должен был прервать retry-каскад до прокси-стадии. Похоже, один из путей (возможно, формат-путь или always-ask путь) не покрыт guard'ом — либо это регресс после последующих мерджей.

**Дополнительно** (см. #459): на пути обработки PERMANENT_UNAVAILABLE в `down_and_up.py` сейчас кидает `TypeError: send_to_user() got an unexpected keyword argument 'parse_mode'` — это маскирует friendly-сообщение, поэтому «работу» UX-обработки по этим ошибкам сейчас проверить нельзя. После фикса #459 стоит повторно оценить, доходит ли friendly-сообщение и не запускается ли прокси-фолбэк.

Issue переоткрыт, т.к. закрыт как fixed, не помечен wontfix/not-planned, а ошибки того же типа воспроизводятся.

**Comment by chelaxian** [comment]
Recurrence fixed in commit 7ccba6b (branch `proger4ever-prs`, pushed).

**Root cause of the recurrence (confirmed in code):** the original fix 7fcf45c added the `'page needs to be reloaded'` fast-fail guard to `get_video_formats` (yt_dlp_hook.py) and to the download-phase error handler (down_and_up.py:2655). However, the **extract phase** inside `down_and_up()` (the local `extract_info_operation` used before downloading) had no such guard: any non-Cloudflare DownloadError went straight to `try_with_proxy_fallback(...)` → the observed `Proxy fallback failed: ... The page needs to be reloaded` lines, i.e. a full proxy rotation for an error that proxies cannot fix.

**Fix:** the extract-phase error handler now reuses `_is_permanent_unavailable` / `_is_rate_limited` from `yt_dlp_hook` and re-raises immediately when the error matches, preserving the original error text so the outer classifier still shows the clean EXTRACTOR_ERROR message. The proxy/impersonate fallback storm is skipped entirely.

Note: the friendly message for this path was additionally broken by #459 (`send_to_user` TypeError) — that is fixed separately in 75607f4, so the UX metrics for PERMANENT_UNAVAILABLE handling will become trustworthy again.

Closing as completed.

**Comment by chelaxian** [comment]
Регрессия: ошибка вернулась. За 24ч (2026-09-05, инстанс DE) — 24 случая 'The page needs to be reloaded' в get_video_formats и DownloadError. Проблема воспроизводится после закрытия (2026-08-30), т.е. исправление не устранило её полностью — вероятно, нужно принудительное обновление yt-dlp или обход через другой клиент (INNERTUBE_CONTEXT).
